/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as MergedRouteImport } from './routes/merged'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const MergedRoute = MergedRouteImport.update({
  id: '/merged',
  path: '/merged',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/magazine': typeof MagazineRoute
  '/merged': typeof MergedRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/magazine': typeof MagazineRoute
  '/merged': typeof MergedRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/magazine': typeof MagazineRoute
  '/merged': typeof MergedRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book' | '/magazine' | '/merged' | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book' | '/magazine' | '/merged' | '/terminal'
  id: '__root__' | '/' | '/book' | '/magazine' | '/merged' | '/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  MagazineRoute: typeof MagazineRoute
  MergedRoute: typeof MergedRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merged': {
      id: '/merged'
      path: '/merged'
      fullPath: '/merged'
      preLoaderRoute: typeof MergedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  MagazineRoute: MagazineRoute,
  MergedRoute: MergedRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
